root: true
env:
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"
rules:
  node/no-unsupported-features/es-syntax : [
      "error",
      { ignores: ["modules"] },
    ]
  no-console: ["warn", { allow: ["warn", "error"] }] 