# Пользователи
## Создать нового пользователя

POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Leo",
  "email": "test7@gmail.com",
  "avatarPath": "alloha.jpg",
  "password": "blablabla123",
  "userStatus": "regular"
}

###

## Авторизовать пользователя

POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "poop"
}

###

## Отправить изображение

POST http://localhost:8080/users/65bffd191c02bb6ef28df3ab/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/aleksandrvasilev/Desktop/2024-02-26 20.53.10.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
###

## Проверить токен пользователя
GET http://localhost:8080/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsIm5hbWUiOiJLaW0iLCJpZCI6IjY1ZDI0ZjBjNTRmZWY2ZGI1M2Q1OTZhNSIsImlhdCI6MTcwOTM5NTMwMywiZXhwIjoxNzA5NTY4MTAzfQ.123_Bj0iKfSgquhrf3BTG-ZbG906dhGlQeIC1njhMSc

##
###

## Добавление предложения в избранное пользователя

POST http://localhost:8080/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsIm5hbWUiOiJLaW0iLCJpZCI6IjY1ZDI0ZjBjNTRmZWY2ZGI1M2Q1OTZhNSIsImlhdCI6MTcwOTQwMzIzNCwiZXhwIjoxNzA5NTc2MDM0fQ.Z8D_dzmB527UX6r8r3vzScOD0o3NKa_qElgXc2WBZl0

{
  "offerId": "65e37077ccfca4b5583f0230"
}