# Пользователи
## Создать нового пользователя

POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Josh",
  "email": "test9@gmail.com",
  "avatarPath": "alloha.jpg",
  "password": "blablabla123",
  "userStatus": "regular"
}

###

## Авторизовать пользователя

POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test9@gmail.com",
  "password": "blablabla123"
}

###

## Отправить изображение

POST http://localhost:8080/users/65bffd191c02bb6ef28df3ab/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/aleksandrvasilev/Desktop/2024-02-26 20.53.10.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
###

## Проверить токен пользователя
GET http://localhost:8080/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsIm5hbWUiOiJLaW0iLCJpZCI6IjY1ZDI0ZjBjNTRmZWY2ZGI1M2Q1OTZhNSIsImlhdCI6MTcwOTM5NTMwMywiZXhwIjoxNzA5NTY4MTAzfQ.123_Bj0iKfSgquhrf3BTG-ZbG906dhGlQeIC1njhMSc

##
###

## Добавление предложения в избранное пользователя

POST http://localhost:8080/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q5QGdtYWlsLmNvbSIsIm5hbWUiOiJKb3NoIiwiaWQiOiI2NWUzYWNkMzdiYzVhY2ZjZWVmNWRmOGUiLCJpYXQiOjE3MDk0MjA0MDIsImV4cCI6MTcwOTU5MzIwMn0.Lrr3B23XugHqlTOZ1yTY9-02Y8e2mp1hcVwr_lrDxMk

{
  "offerId": "65e3b32abaf215aa1dd57ce3"
}

##
###

## Удаление предложения из избранного пользователя

DELETE http://localhost:8080/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q3QGdtYWlsLmNvbSIsIm5hbWUiOiJMZW8iLCJpZCI6IjY1ZTM5ZWM3MTdiYmRhNTk4OGQ3MTJkMSIsImlhdCI6MTcwOTQxNjE0NCwiZXhwIjoxNzA5NTg4OTQ0fQ.fEGmGoU0Izfwe0_VC2t7Lqh_FP1kQIIUpX7GZk9AaPc

{
  "offerId": "65e39eee17bbda5988d712d4"
}