# Категории
## Получить список объявлений
GET http://localhost:8080/housings HTTP/1.1
Content-Type: application/json

###

## Добавить новое объявление
POST http://localhost:8080/housings HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q3QGdtYWlsLmNvbSIsIm5hbWUiOiJMZW8iLCJpZCI6IjY1ZTM5ZWM3MTdiYmRhNTk4OGQ3MTJkMSIsImlhdCI6MTcwOTQxNjE0NCwiZXhwIjoxNzA5NTg4OTQ0fQ.fEGmGoU0Izfwe0_VC2t7Lqh_FP1kQIIUpX7GZk9AaPc

{
  "authorId": "65e39555ded522bccf097ffe",
  "postDate": "2024-03-01T12:15:45.279Z",
  "title": "les lengendary hotel",
  "description": "Oh my god this is unbelievable!",
  "city": "Paris",
  "preview": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.dezeen.com%2F2011%2F10%2F26%2Fmaison-champs-elysees-by-maisonVaw0E2dsoTCPDO0rihtYQDFQAAAAAdAAAAABAI",
  "images": ["https://wwww.booking.com/test_photo1", "https://wwww.booking.com/test_photo2", "https://wwww.booking.com/test_photo3", "https://wwww.booking.com/test_photo4", "https://wwww.booking.com/test_photo5"],
  "housingType": "hotel",
  "rooms": 4,
  "guests": 4,
  "price": 666,
  "isPremium": true,
  "rating": 1,
  "features": ["Washer", "Towels"],
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
    }
}

###

# Категории
## Получить объявление по id
GET http://localhost:8080/housings/65e3848806ccb69f20eb425e HTTP/1.1
Content-Type: application/json

###

# Категории
## Получить список премиум объявлений по конкретному городу
GET http://localhost:8080/housings/premium?city=amsterdam HTTP/1.1
Content-Type: application/json

###

# Категории
## Получить список избранных объявлений
GET http://localhost:8080/housings/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Q5QGdtYWlsLmNvbSIsIm5hbWUiOiJKb3NoIiwiaWQiOiI2NWUzYWNkMzdiYzVhY2ZjZWVmNWRmOGUiLCJpYXQiOjE3MDk0MTk3NTEsImV4cCI6MTcwOTU5MjU1MX0.6fU_ZwEapnM8ufThadrrFMjcU_4mFxPvVyoYyzEz-_Q
###
