# Категории
## Получить список объявлений
GET http://localhost:8080/housings HTTP/1.1
Content-Type: application/json

###

## Добавить новое объявление
POST http://localhost:8080/housings HTTP/1.1
Content-Type: application/json

{
  "authorId": "65d2647d39eecdd3d5ea5ff4",
  "postDate": "2024-02-18T12:15:45.279Z",
  "title": "Your Paris Nightmare",
  "description": "You don't want to know how bad it is",
  "city": "Paris",
  "preview": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.dezeen.com%2F2011%2F10%2F26%2Fmaison-champs-elysees-by-maison-martin-margiela%2F&psig=AOvVaw0E2ds7EEMpRikolJzpYQgp&ust=1708358480650000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPDO0rihtYQDFQAAAAAdAAAAABAI",
  "images": ["https://wwww.booking.com/test_photo1", "https://wwww.booking.com/test_photo2", "https://wwww.booking.com/test_photo3", "https://wwww.booking.com/test_photo4", "https://wwww.booking.com/test_photo5"],
  "housingType": "hotel",
  "rooms": 4,
  "guests": 4,
  "price": 666,
  "isPremium": true,
  "isFavorite": false,
  "rating": 1,
  "features": ["Washer", "Towels"],
  "location": "48.85661 2.351499"
}

###

# Категории
## Получить объявление по id
GET http://localhost:8080/housings/65de60e5fb6972638a HTTP/1.1
Content-Type: application/json

###

# Категории
## Получить список премиум объявлений по конкретному городу
GET http://localhost:8080/housings/premium?city=amsterdam HTTP/1.1
Content-Type: application/json

###

